// <auto-generated />
using CIDET.InfraStructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIDET.InfraStructure.DAL.Migrations
{
    [DbContext(typeof(CIDETDataContext))]
    [Migration("20210528174430_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CIDET.Domain.Entity.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Antioquia"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Atlántico"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Bolívar"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Bogotá"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Chocó"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Cundinamarca"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "La Guajira"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Nariño"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Norte de Santander"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Quindío"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "San Andrés y Providencia"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Santander"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Sucre"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Tolima"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Valle del Cauca"
                        });
                });

            modelBuilder.Entity("CIDET.Domain.Entity.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoDANE")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsDistrito")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoDANE");

                    b.HasIndex("Nombre");

                    b.ToTable("Municipios");
                });
#pragma warning restore 612, 618
        }
    }
}
